// /lib/products.ts

export const products = [
  {
    id: 'rose-001',
    name: 'Красная роза',
    price: 1200,
    image: '/flowers/rose.jpg',
    description: "Красная роза — традиционный символ любви и изящества.",
    availability: true,
    oldPrice: null,
    discount: 0, // скидка 0%
  },
  {
    id: 'tulip-002',
    name: 'Жёлтый тюльпан',
    price: 950,
    image: '/flowers/tulip.jpg',
    description: 'Жёлтый тюльпан — воплощение радости и весеннего настроения.',
    availability: true,
    oldPrice: 1100,
    discount: 25, // Скидка 25%
  },
  {
    id: 'orchid-003',
    name: 'Орхидея',
    price: 1500,
    image: '/flowers/orchid.jpg',
    description: 'Орхидея — утончённый подарок для важных моментов.',
    availability: false,
    oldPrice: null,
    discount: 0,
  },
  {
    id: 'sunflower-004',
    name: 'Подсолнух',
    price: 800,
    image: '/flowers/sunflower.jpg',
    description: 'Яркий подсолнух, который наполняет день теплом и светом.',
    availability: true,
    oldPrice: null,
    discount: 10,
  },
  {
    id: 'lily-005',
    name: 'Лилия',
    price: 1300,
    image: '/flowers/lily.jpg',
    description: '«Изящная лилия с восхитительным ароматом.',
    availability: true,
    oldPrice: 1450,
    discount: 5,
  },
  {
    id: 'daisy-006',
    name: 'Маргаритка',
    price: 700,
    image: '/flowers/daisy.jpg',
    description: '«Скромная и очаровательная маргаритка — символ чистоты и невинности.',
    availability: true,
    oldPrice: null,
    discount: 0,
  },
  {
    id: 'peony-007',
    name: 'Пион',
    price: 1600,
    image: '/flowers/peony.jpg',
    description: 'Роскошный пион с большими бутонами и великолепным ароматом.',
    availability: true,
    oldPrice: null,
    discount: 15,
  },
  {
    id: 'carnation-008',
    name: 'Гвоздика',
    price: 950,
    image: '/flowers/carnation.jpg',
    description: 'Классическая гвоздика, представлена в разнообразных оттенках.',
    availability: true,
    oldPrice: 1050,
    discount: 10,
  },
];