// /lib/products.ts

export const products = [
  {
    id: 'rose-001',
    name: 'Красная роза',
    price: 1200,
    image: '/flowers/rose.jpg',
    description: 'Классическая красная роза - символ любви и красоты.',
    availability: true,
    oldPrice: null,
    discount: 0, // Нет скидки
  },
  {
    id: 'tulip-002',
    name: 'Жёлтый тюльпан',
    price: 950,
    image: '/flowers/tulip.jpg',
    description: 'Яркий жёлтый тюльпан, дарящий радость и весеннее настроение.',
    availability: true,
    oldPrice: 1100,
    discount: 15, // Скидка 15%
  },
  {
    id: 'orchid-003',
    name: 'Орхидея',
    price: 1500,
    image: '/flowers/orchid.jpg',
    description: 'Изысканная орхидея - элегантный подарок для особых случаев.',
    availability: false,
    oldPrice: null,
    discount: 0,
  },
  {
    id: 'sunflower-004',
    name: 'Подсолнух',
    price: 800,
    image: '/flowers/sunflower.jpg',
    description: 'Весёлый подсолнух, наполняющий день солнечным светом.',
    availability: true,
    oldPrice: null,
    discount: 10,
  },
  {
    id: 'lily-005',
    name: 'Лилия',
    price: 1300,
    image: '/flowers/lily.jpg',
    description: 'Нежная лилия с прекрасным ароматом.',
    availability: true,
    oldPrice: 1450,
    discount: 5,
  },
  {
    id: 'daisy-006',
    name: 'Маргаритка',
    price: 700,
    image: '/flowers/daisy.jpg',
    description: 'Простая и милая маргаритка, символ чистоты и невинности.',
    availability: true,
    oldPrice: null,
    discount: 0,
  },
  {
    id: 'peony-007',
    name: 'Пион',
    price: 1600,
    image: '/flowers/peony.jpg',
    description: 'Пышный пион с крупными бутонами и чудесным ароматом.',
    availability: true,
    oldPrice: null,
    discount: 20,
  },
  {
    id: 'carnation-008',
    name: 'Гвоздика',
    price: 950,
    image: '/flowers/carnation.jpg',
    description: 'Традиционная гвоздика, доступная в различных цветах.',
    availability: true,
    oldPrice: 1050,
    discount: 0,
  },
];